Added RenderGeometry handling and RenderMesh method
BHoM/TriangleNet_Toolkit pull request #106
Opened 2023-02-06 19:24 UTC by enarhi

### Issues addressed by this PR

Closes #107

Added handling and method for getting RenderMesh from RenderGeometry.

### Test files
[test file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/TriangleNet_Toolkit/%23107-RenderMeshFromRenderGeometry/[RenderMeshFromRenderGeometry.gh](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/TriangleNet_Toolkit/%23107-RenderMeshFromRenderGeometry/RenderMeshFromRenderGeometry.gh?csf=1&web=1&e=YO1Oyk)?csf=1&web=1&e=YO1Oyk)

### Changelog

### Additional comments

2023-02-06 22:06 UTC, FraserGreenroyd requested changes
Will leave functionality review to @alelom - but the issue it's closing doesn't seem to exist? I'm thinking it should be #105 @enarhi but could you confirm and update as necessary?

2023-02-06 22:06 UTC, FraserGreenroyd commented on TriangleNet_Engine/Compute/Representation/RenderMesh/Other/RenderGeometry.cs
> + * Copyright (c) 2015 - 2022, the respective contributors. All rights reserved.
```suggestion
 * Copyright (c) 2015 - 2023, the respective contributors. All rights reserved.
```

2023-02-07 09:40 UTC, alelom commented on TriangleNet_Engine/Compute/Representation/RenderMesh/Other/RenderGeometry.cs
> +                BH.Engine.Base.Compute.RecordError("Cannot compute the mesh of a null render geometry object.");
```suggestion
                BH.Engine.Base.Compute.RecordError($"Cannot compute the mesh of a null {nameof(RenderGeometry)} object.");
```

2023-02-07 09:58 UTC, alelom requested changes
Just a small change requested, code looks good and functionality works well with the provided test script.

2023-02-07 16:01 UTC, enarhi commented
@BHoMBot check compliance

2023-02-07 16:02 UTC, enarhi commented on TriangleNet_Engine/Compute/Representation/RenderMesh/Other/RenderGeometry.cs
> +                BH.Engine.Base.Compute.RecordError("Cannot compute the mesh of a null render geometry object.");
updated with improved error, thanks!

2023-02-07 16:04 UTC, enarhi commented on TriangleNet_Engine/Compute/Representation/RenderMesh/Other/RenderGeometry.cs
> + * Copyright (c) 2015 - 2022, the respective contributors. All rights reserved.
fixed

2023-02-07 16:11 UTC, enarhi commented
@BHoMBot check compliance

2023-02-07 16:28 UTC, enarhi commented
@BHoMBot check compliance

2023-02-07 17:23 UTC, enarhi commented
closing, replaced by #107

2023-02-07 17:25 UTC, FraserGreenroyd commented
Replaced by #107

2023-02-07 17:25 UTC, closed without merging