Added RenderGeometry handling and RenderMesh method from RenderGeometry
BHoM/TriangleNet_Toolkit pull request #107
Opened 2023-02-07 17:23 UTC by enarhi

### Issues addressed by this PR

Closes #105 

Added handling and method for getting RenderMesh from RenderGeometry.

### Test files
[test file](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FTriangleNet%5FToolkit%2F%23107%2DRenderMeshFromRenderGeometry&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b)

2023-02-07 17:24 UTC, enarhi commented
@BHoMBot check compliance

2023-02-07 17:27 UTC, FraserGreenroyd requested changes

2023-02-07 17:27 UTC, FraserGreenroyd commented on TriangleNet_Engine/Compute/Representation/RenderMesh/Other/RenderGeometry.cs
> +
```suggestion
```

2023-02-07 17:27 UTC, FraserGreenroyd commented on TriangleNet_Engine/Compute/Representation/RenderMesh/Other/RenderGeometry.cs
> +        public static BH.oM.Graphics.RenderMesh RenderMesh(this RenderGeometry renderGeometry, RenderMeshOptions renderMeshOptions = null)
I think file name needs to be updated looking at the code?

2023-02-07 22:49 UTC, enarhi commented
@BHoMBot check compliance

2023-02-07 22:59 UTC, FraserGreenroyd approved these changes
I'm happy from a DevOps perspective after code review. Will let @alelom do a final functionality review for a final bit of testing 😄

2023-02-23 11:24 UTC, alelom approved these changes
Approving functionality from test script, also code looks fine.

2023-02-23 15:31 UTC, enarhi commented
@BHoMBot check required

2023-02-23 19:06 UTC, FraserGreenroyd commented
@BHoMBot check required

2023-02-23 19:47 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests
@BHoMBot check ready-to-merge

2023-02-23 19:52 UTC, merged